<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-01EKQH3" failures="0" tests="8" name="com.abc.testcases.HomePageTestCases" time="0.010" errors="1" timestamp="2022-12-31T18:26:10 IST" skipped="7">
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC7" time="0.000">
    <skipped/>
  </testcase> <!-- TC7 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC2" time="0.010">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentReports.createTest(String)&quot; because &quot;com.abc.reporter.Reporter.report&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.createTest(String)" because "com.abc.reporter.Reporter.report" is null
at com.abc.reporter.Reporter.createTest(Reporter.java:33)
at com.abc.testcases.HomePageTestCases.TC2(HomePageTestCases.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC2 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC1" time="0.000">
    <skipped/>
  </testcase> <!-- TC1 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC5" time="0.000">
    <skipped/>
  </testcase> <!-- TC5 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC2" time="0.000">
    <skipped/>
  </testcase> <!-- TC2 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC6" time="0.000">
    <skipped/>
  </testcase> <!-- TC6 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC3" time="0.000">
    <skipped/>
  </testcase> <!-- TC3 -->
  <system-out/>
  <testcase classname="com.abc.testcases.HomePageTestCases" name="TC4" time="0.000">
    <skipped/>
  </testcase> <!-- TC4 -->
  <system-out/>
</testsuite> <!-- com.abc.testcases.HomePageTestCases -->
